- name: Up date servers pre-task
  hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOS)
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
      ignore_errors: true

    - name: install updates (Ubuntu)
      apt:
         upgrade: dist
         update_cache: yes
      when: ansible_distribution == "Ubuntu"
      ignore_errors: true

    - name: install updates (RedHat)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution_major_version == "8"
      ignore_errors: true

  tasks:
    - name: Add user cofe
      ansible.builtin.user:
        name: cofe
        comment: Cofe Vargo
        uid: 1020
        shell: /bin/bash





