# This script is meant to run after boostrap.yml initial configuration run

- name: Up date all servers
  hosts: all
  become: true
  pre_tasks:
  - name: install updates
    package:
      update_cache: yes
    changed_when: false          # Allow control over what is considered as change
    ignore_errors: true

- hosts: all
  become: true
  tasks:

  - name: Add ssh key for cofe # to enable password less log in to server, cofe user created in bootstrap.yml
    tags: always,cofe
    authorized_key:
      user: cofe        # serve as place-holder in case key is compromised and needs to be removed, using state:absent
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH3Db/5f2cXO4n3+NqALwYM05ITMUxMtkflrz9L1QnwP ansible"

  - name: install terraform
    unarchive: # module to unzip file after download
      src: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_arm64.zip
      dest: /usr/local/bin
      remote_src: yes   # Downloaded from the internet
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php for ubuntu
    tags: apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
    ignore_errors: true

  - name: Install latest httpd and php for centos and rhel
    tags: httpd,apache,centos,rhel
    package:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS","rhel"
    ignore_errors: true

  - name: Start firewalld and httpd (centos,rhel)
    tags: apache,httpd,centos,rhel
    service:
      name: "{{item}}"
      state: started
      enabled: yes
    with_items:
      - firewalld
      - httpd
    when: ansible_distribution == "CentOS","rhel"

  - name: Copy default file for site
    tags: apache2,ubuntu,centos,rhel
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'





