- name: Up date servers pre-task
  hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOS)
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
      ignore_errors: true

    - name: install updates (Ubuntu)
      apt:
         upgrade: dist
         update_cache: yes
      when: ansible_distribution == "Ubuntu"
      ignore_errors: true

    - name: install updates (RedHat)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution_major_version == "8"
      ignore_errors: true

  tasks:
    - name: Add user cofe
      ansible.builtin.user:
        name: cofe
        comment: Cofe Vargo
        uid: 1020
        shell: /bin/bash
        create_home: true

    - name: Create ansible home directory
      file:
        path: /home/ansible
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: Create a file in /etc/ directory
      file:
        path: /etc/ansible-testfile.txt
        state: touch
        mode: u=rwx,g=rw,o=rw




