- name: Up date servers re-task
  hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOS)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
      ignore_errors: true

    - name: install updates (Ubuntu)
      apt:
         upgrade: dist
         update_cache: yes
      when: ansible_distribution == "Ubuntu"

- name: install or uninstall packages as need be
  hosts: web_servers
  become: true
  tasks:
  - name: install latest version of apache and php
    ansible.builtin.package:
     name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
     state: latest
     update_cache: yes
    ignore_errors: true

- name: install mariadb packages
  hosts: db_servers
  become: true
  tasks:
  - name: install latest version of mariadb
    ansible.builtin.package:
     name:
        - "{{ mariadb_package }}"
     state: late
    ignore_errors: true

- name: install samba packages
  hosts: file_servers
  become: true
  tasks:
  - name: install latest version of samba
    ansible.builtin.package:
     name: samba
     state: latest
    ignore_errors: true




