- name:
    hosts: all
    become: true
    pre_tasks:

    - name: install updates (CentOS)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install or uninstall packages as need be
      hosts: web_servers
      become: true
      tasks:

       - name: install latest version of apache and php
         ansible.builtin.package:
           name:
            - "{{ apache_package }}"
            - "{{ php_package }}"
           state: latest
           update_cache: yes
           ignore_errors: true







