# This script is meant to run after boostrap.yml initial configuration run

- name: OS specific play - PRE
  hosts: foreman_centos7
  become: true
  roles:
    - centos7-pre

- name: Pre-task up date all servers
  hosts: all
  become: true
  pre_tasks:
  - name: update all hosts
    package:
      update_cache: yes
    changed_when: false          # Allow control over what is considered as change
    ignore_errors: true

- name: install base configuration
  hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers



