
- name: OS_common pre-config plays
  hosts: all
  become: true
  roles:
    - os_common_pre

- name: CentOS7 pre-config plays
  hosts: foreman_centos7
  become: true
  roles:
    - centos7-pre

- name: install base configuration
  hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers



