- name: Up date servers pre-task
  hosts: all
  become: true
  pre_tasks:

    - name: install updates (CentOS)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
      ignore_errors: true

    - name: install updates (Ubuntu)
      apt:
         upgrade: dist
         update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: install latest version of apache and php
      ansible.builtin.package:
        name:
         - "{{ apache_package }}"
         - "{{ php_package }}"
        state: latest
      ignore_errors: true

- hosts: db_servers
  become: true
  tasks:
  - name: install latest version of mariadb
    ansible.builtin.package:
      name:
      - "{{ mariadb_package }}"
      state: late
    ignore_errors: true

- hosts: file_servers
  become: true
  tasks:
    - name: install latest version of samba
      ansible.builtin.package:
        name: samba
        state: latest
      ignore_errors: true




